import { Trip } from '@/types/trip'
import { TripAIContent } from '@/lib/validations/trip-ai-content'

export function buildOfflineHtml(trip: Trip, content: TripAIContent): string {
  const timelineHtml = content.timeline.days
    .map(
      (day) => `
        <h3>Day ${day.day}: ${day.title}</h3>
        <ul>${day.activities.map((a) => `<li>${a}</li>`).join('')}</ul>`
    )
    .join('')

  const packingHtml = content.packingChecklist.categories
    .map(
      (cat) => `
        <h4>${cat.category}</h4>
        <ul>${cat.items.map((i) => `<li>☐ ${i}</li>`).join('')}</ul>`
    )
    .join('')

  const emergencyHtml = content.emergencyInfo.items
    .map((item) => `<li><strong>${item.name}</strong> (${item.type.replace('_', ' ')}): ${item.detail}</li>`)
    .join('')

  const dateLabel =
    trip.start_date && trip.end_date
      ? `${trip.start_date} to ${trip.end_date}`
      : trip.duration_days
      ? `${trip.duration_days} day${trip.duration_days > 1 ? 's' : ''} (dates not set)`
      : 'Dates not set'

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${trip.title} — Offline Plan</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 700px; margin: 40px auto; padding: 0 20px; color: #1f2937; }
  h1 { font-size: 1.5rem; } h2 { border-bottom: 2px solid #e5e7eb; padding-bottom: 6px; margin-top: 2rem; }
  h3 { margin-bottom: 4px; } h4 { margin-bottom: 4px; color: #374151; }
  ul { margin-top: 0; } li { margin-bottom: 2px; }
  .meta { color: #6b7280; font-size: 0.9rem; }
</style></head>
<body>
  <h1>${trip.title}</h1>
  <p class="meta">${trip.source} → ${trip.destinations.join(' → ')}<br>
  ${dateLabel} · ${trip.travelers} traveler(s) · ${trip.budget} ${trip.currency}</p>

  <h2>Itinerary</h2>
  ${timelineHtml}

  <h2>Packing Checklist</h2>
  ${packingHtml}

  <h2>Emergency Information</h2>
  <ul>${emergencyHtml}</ul>

  <p class="meta" style="margin-top: 3rem;">Downloaded for offline use — generated by your AI Travel Intelligence Platform.</p>
</body></html>`
}